openapi: 3.0.0
info:
  title: ToDo API
  description: API for managing a bookstore
  version: 1.0.0
servers:
  - url: https://api.todo.com/v1
paths:
  /todo:
    get:
      summary: Get a list of todos
      responses:
        '200':
          description: A successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    duration_in_minutes:
                      type: integer
                    frequency_per_month:
                      type: integer
                    how_much_work:
                      type: integer
